# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '30 6,18 * * *'    # Job runs at 7:30 and 19:30 WAT everyday 
  
jobs:
  postmantesttest: 

    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm i -g newman newman-reporter-htmlextra
    - run: newman run LearnPostman.postman_collection.json -e QA.postman_environment.json -r htmlextra
    - run: ls ./newman
    - run: mv ./newman/*.html ./newman/postmantestreport.html
    # Upload the contents of Test Results directory to workspace
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      if: always()
      with:
       name: RunReports
       path: /home/runner/work/AutomatePostmanTest/AutomatePostmanTest/newman
    - name: Send mail to stakeholders
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
         # mail server settings
         server_address: smtp-mail.outlook.com
         server_port: 587
         # user credentials
         username:
         password:
         # email subject
         subject: Postman test test report - ${{ job.status }}
         # email body as text
         body: Hello Team, please find attached test run report
         # comma-separated string, send email to
         to: ogunnubiseyi@gmail.com, omarookolosio94@gmail.com
         # from email name
         from: API Test
         attachments: /home/runner/work/AutomatePostmanTest/AutomatePostmanTest/newman/postmantestreport.html
